export const GET_USER_SELECT_INPUT = 'GET_USER_SELECT_INPUT';
export const GET_USER_SEARCH_INPUT = 'GET_USER_SEARCH_INPUT';
export const GET_POSTS = 'GET_POSTS';
export const CLEAR_POSTS = 'CLEAR_POSTS';
